# Generated by Django 2.2.12 on 2020-10-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='用户名')),
                ('real_name', models.CharField(max_length=30, verbose_name='真实姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('avatar', models.ImageField(null=True, upload_to='avatar', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user_user_profile',
            },
        ),
    ]
