# Generated by Django 2.2.12 on 2020-11-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_orderprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprofile',
            name='is_alive',
            field=models.BooleanField(default=False, verbose_name='是否支付'),
        ),
    ]
