# Generated by Django 2.2.12 on 2020-11-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201106_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderprofile',
            old_name='is_alive',
            new_name='is_pay',
        ),
    ]
