# Generated by Django 2.2.12 on 2020-11-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201106_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprofile',
            name='order_id',
            field=models.CharField(default=1, max_length=100, verbose_name='订单号'),
        ),
    ]
