# Generated by Django 2.2.12 on 2020-11-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_orderprofile_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='无', max_length=30, verbose_name='昵称'),
        ),
    ]
