# Generated by Django 2.2.12 on 2020-11-02 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelProfile',
            fields=[
                ('hotelname', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='酒店名')),
                ('hotelphone', models.CharField(max_length=11, verbose_name='热线电话')),
                ('hotelimageoutside', models.ImageField(null=True, upload_to='', verbose_name='酒店外观')),
                ('hotelimageinside', models.ImageField(null=True, upload_to='', verbose_name='酒店内部')),
                ('hotelplace', models.CharField(max_length=30, verbose_name='酒店城市所在')),
                ('hoteladdress', models.CharField(max_length=100, verbose_name='酒店地址')),
                ('hotelhotpoint', models.IntegerField(default=0, verbose_name='酒店热度')),
                ('is_alive', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'db_table': 'hotel_hotel_profile',
            },
        ),
        migrations.CreateModel(
            name='RoomProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnumber', models.CharField(max_length=30, verbose_name='房间号')),
                ('roomimageinside01', models.ImageField(null=True, upload_to='', verbose_name='房间内部01')),
                ('roomimageinside02', models.ImageField(null=True, upload_to='', verbose_name='房间内部02')),
                ('roomprice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='房间价格')),
                ('is_alive', models.BooleanField(default=True, verbose_name='是否可用')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.HotelProfile')),
            ],
            options={
                'db_table': 'hotel_room_profile',
            },
        ),
    ]
